add missing require 'singleton'
require 'dbus_clients/backend_exception'
NameError: uninitialized constant DbusClients::ExceptionRegister::Singleton
	from /usr/lib/ruby/vendor_ruby/1.8/dbus_clients/backend_exception.rb:21
	from (irb):1:in `require'
	from (irb):1
	from :0